export default[
	{
		problem:'001.jpg',
		answer:'一刀两断',
		disturb:'一刀两断文字书写墨水难行',
		description:'比喻断绝关系。形容行事乾脆爽快。'
	},
	{
		problem:'002.jpg',
		answer:'一日千里',
		disturb:'一日千里走路行步阳山示炸',
		description:'形容良马跑得很快。比喻进步神速或事业发展得很快。'
	},
	{
		problem:'004.jpg',
		answer:'一目了然',
		disturb:'一目了然眼睛看视文字平洗',
		description:'看一眼就完全清楚明白。'
	},
	{
		problem:'008.jpg',
		answer:'一见锺情',
		disturb:'一见锺情射箭爱字中穿赞脸',
		description:'喻男女双方第一次见面便互相喜爱。'
	},
	{
		problem:'010.jpg',
		answer:'一刻千金',
		disturb:'一刻千金头转向嚣浮轻巧鹰',
		description:'一刻时光，价值千金。形容时间非常宝贵。'
	},
	{
		problem:'h.png',
		answer:'表里如一',
		disturb:'表里如一回口声同说吞凹凸',
		description:'表面和内心都一样，形容言行和品质完全一致'
	},
	{
		problem:'pg.png',
		answer:'前仆后继',
		disturb:'前仆后继街续左右东西倒歪',
		description:'前面的人倒下了，后面的人继续跟上去。英勇斗争，不怕牺牲'
	},
	{
		problem:'cp.png',
		answer:'横冲直撞',
		disturb:'横冲直撞上下滑偏移浪挡闯',
		description:'乱冲乱撞，蛮横无理。'
	},
	{
		problem:'jpd.png', 
		answer:'杀鸡取卵',
		disturb:'杀鸡取卵引鸠止渴因小失大',
		description:'为了要得到鸡蛋，不惜把鸡杀了。比喻贪图眼前的好处而不顾长远利益。'
	},
	{
		problem:'009.png', 
		answer:'鱼贯而出',
		disturb:'鱼贯而出脱颖游探口冲倾巢',
		description:'如游鱼首尾相接连，一个挨著一个陆续而出。'
	},
	{
		problem:'005.png', 
		answer:'四通八达',
		disturb:'四通八达面道路东西南北交',
		description:'四面八方都有路可通。形容交通极便利。也形容通向各方。'
	},
	{
		problem:'003.png', 
		answer:'网开一面',
		disturb:'网开一面破之雅独当缘悭漏',
		description:'把捕禽的网撤去三面，只留一面。比喻采取宽大态度，给人一条出路。'
	},
	{
		problem:'006.png', 
		answer:'头重脚轻',
		disturb:'头重脚轻失去平衡山岩炭送',
		description:'头脑发胀，脚下无力。形容身体不适。也比喻基础不牢固。'
	},
	{
		problem:'007.png', 
		answer:'命悬一线',
		disturb:'命悬一线两败俱伤生机吊起',
		description:'处境危险，随时可能丧失生命。'
	},
	{
		problem:'011.png', 
		answer:'鱼目混珠',
		disturb:'鱼目混珠眼睛龙杂泥沙俱下',
		description:'鱼目：鱼眼睛；混：混同，冒充。拿鱼眼睛冒充珍珠。比喻以假乱真，以次充好。'
	},
	{
		problem:'012.png', 
		answer:'水滴石穿',
		disturb:'水滴石穿雪崩效应积习沉舟',
		description:'水不停地滴，石头也能被滴穿。比喻只要有恒心，不断努力，事情就一定能成功。'
	},
	{
		problem:'013.png', 
		answer:'穷困潦倒',
		disturb:'穷困潦倒苦恨繁鬓瓦灶绳床',
		description:'贫穷、困难；潦倒：失意。生活贫困，失意颓丧。'
	},
	{
		problem:'014.png', 
		answer:'狗急跳墙',
		disturb:'狗急跳墙人急烧香困兽犹斗',
		description:'比喻走投无路时采取不顾 一切的行动。'
	},
	{
		problem:'015.png', 
		answer:'掩人耳目',
		disturb:'掩人耳目盗铃事迹显然遮骗',
		description:'遮着别人的耳朵和眼睛，比喻以假象蒙骗别人。'
	},
	{
		problem:'016.png', 
		answer:'指鹿为马',
		disturb:'指鹿为马颠倒黑角乌牛高大',
		description:'把鹿说成马。比喻故意颠倒黑白，混淆是非。'
	},
	{
		problem:'017.png', 
		answer:'老牛舐犊',
		disturb:'老牛舐犊添亲小母牧采薪情',
		description:'舐：舔；犊：小牛。老牛舔小牛。比喻父母疼爱子女。'
	},
	{
		problem:'018.png', 
		answer:'春色满园',
		disturb:'春色满园游不值笋怒发意盎',
		description:'满园都是春天的景色。比喻到处都是欣欣向荣的景象。'
	},
	{
		problem:'019.png', 
		answer:'无中生有',
		disturb:'无中生有事出因无兄盗嫂错',
		description:'把没有说成有。指凭空捏造。'
	},
	{
		problem:'020.png', 
		answer:'独出心裁',
		disturb:'独出心裁别开生面标新立异',
		description:'原指诗文的构思有独到的地方，后来指想出来的办法与众不同。'
	},
	{
		problem:'021.png', 
		answer:'妙笔生花',
		disturb:'妙笔生花聚众滋事下辉飞神',
		description:'比喻杰出的写作才能。'
	},
	{
		problem:'022.png', 
		answer:'开膛破肚',
		disturb:'开膛破肚心如刀割刺入胸腰',
		description:'把一个生物剖开膛，刮开肚来看。'
	},
	{
		problem:'023.png', 
		answer:'苟延残喘',
		disturb:'苟延残喘狗人游泳救死扶伤',
		description:'苟：苟且，勉强；延：延续；残喘：临死前的喘息。勉强拖延一口没断的气。比喻勉强维持生存'
	},
	{
		problem:'024.png', 
		answer:'一石二鸟',
		disturb:'一石二鸟两全其美徒劳无功',
		description:'扔一颗石子打到两只鸟。比喻做一件事情得到两种好处。'
	},
	{
		problem:'025.png', 
		answer:'针锋相对',
		disturb:'针锋相对唇枪舌将逆来顺受',
		description:'针尖对针尖。比喻双方意见、观点等尖锐对立'
	},
	{
		problem:'026.png', 
		answer:'山高水长',
		disturb:'山高水长远相隔天万古流芳',
		description:'指山川相隔。形容品格高洁，流传久远。'
	},
	{
		problem:'027.png', 
		answer:'借酒浇愁',
		disturb:'借酒浇愁消喝开车老头洗淋',
		description:'用喝酒来浇灭郁积在心中的气愤或愁闷。'
	},
	{
		problem:'028.png', 
		answer:'酸甜苦辣',
		disturb:'酸甜苦辣红黄相交四大皆空',
		description:'指各种味道，也比喻幸福、痛苦等种种遭遇。'
	},
	{
		problem:'029.jpeg', 
		answer:'莺歌燕舞',
		disturb:'莺歌燕舞鸟语花香鸡犬不宁',
		description:'黄莺歌唱，燕子飞舞，形容大好春光或比喻大好形势：大地春回，～。'
	},
	{
		problem:'030.jpeg', 
		answer:'爱钱如命',
		disturb:'爱钱如命唯利是图仗义疏财',
		description:'某些人贪爱钱财就像吝啬生命一样。形容十分贪婪、刻薄。'
	},
	{
		problem:'031.jpeg', 
		answer:'画地为牢',
		disturb:'画地为牢任其驰骋豪放不羁',
		description:'在地上画个圆圈当作监狱。汉司马迁《报任安书》：“故士有画地为牢，势不可入。” 后用以比喻只许在规定的范围之内活动。'
	},
	{
		problem:'032.jpeg', 
		answer:'指鹿为马',
		disturb:'指鹿为马颠倒是非识龟成鳖',
		description:'指着鹿，说是马。比喻故意颠倒黑白，混淆是非'
	},
	{
		problem:'033.jpeg', 
		answer:'视死如归',
		disturb:'视死如归万不辞舍生忘宁屈',
		description:'把死看得好像回家一样。形容为了正义的事业，不怕死。'
	},
	{
		problem:'034.jpeg', 
		answer:'能曲能伸',
		disturb:'能曲能伸随遇而安宁折不弯',
		description:'能弯曲也能伸展，指人在不得志的时候能忍耐，在得志的时候能施展才干、抱负。'
	},
	{
		problem:'035.jpeg', 
		answer:'刨根问底',
		disturb:'刨根问底寻究锄禾日当午拫',
		description:'刨根问底，比喻追究底细。形容钻研的精神。'
	},
	{
		problem:'036.jpeg', 
		answer:'灯红酒绿',
		disturb:'灯红酒绿花天地纸醉金迷繁',
		description:'形容寻欢作乐的腐化生活，也形容都市或娱乐场所夜晚的繁华景象。'
	},
	{
		problem:'037.jpeg', 
		answer:'矫枉过正',
		disturb:'矫枉过正激首昂视花钱绝后',
		description:'指把弯的东西扳正，又歪到了另一边。比喻纠正错误超过了应有的限度。'
	},
	{
		problem:'038.jpeg', 
		answer:'笼络人心',
		disturb:'笼络人心腹之忧实获我大患',
		description:'笼和络原是羁绊牲口的工具，引伸为用手段拉拢。耍弄手段，拉拢别人。'
	},
	{
		problem:'039.jpeg', 
		answer:'龙马精神',
		disturb:'龙马精神虎猛充沛斗志昂扬',
		description:'唐代李郢《上裴晋公》诗：“四朝忧国鬓如丝，龙马精神海鹤姿。”后用来比喻健旺的精神。'
	},
	{
		problem:'040.jpeg', 
		answer:'无法无天',
		disturb:'无法无天桀骜不羁目王高远',
		description:'形容人毫无顾忌地胡作非为。'
	},
	{
		problem:'041.jpeg', 
		answer:'无与伦比',
		disturb:'无与伦比与类独步一时可拟',
		description:'没有能够比得上的（多含褒义）。'
	},
	{
		problem:'042.jpeg', 
		answer:'望洋兴叹',
		disturb:'望洋兴叹鞭长莫及无能为力',
		description:'《庄子·秋水》记载，河伯（黄河神）自以为大得了不得。后来到了海边，望见无边无际的海洋，才感到自己的渺小，于是仰望着海神，发出了叹息。后比喻做事力量不够或没有条件，而感到无能为力。望洋：仰望的样子。'
	},
	{
		problem:'043.jpeg', 
		answer:'举一反三',
		disturb:'举一反三以微知著触类旁通',
		description:'从一件事物的情况、道理类推而知道许多事物的情况、道理。形容善于类推，能由此及彼。《论语·述而》：“举一隅不以三隅反，则不复也。” 宋朱熹《答胡伯逢书》：“夫告往知来，举一反三，闻一知十者皆适。” 反：类推。'
	},
	{
		problem:'044.png', 
		answer:'火烧眉毛',
		disturb:'火烧眉毛愁苦脸头云涌芦朽',
		description:'比喻非常急迫：～眼下急。这是～的事儿，别这么慢条斯理的。'
	},
	{
		problem:'045.png', 
		answer:'血口喷人',
		disturb:'血口喷人恶意中伤昭冤中枉',
		description:'比喻用极恶毒的语言诬蔑别人。'
	},
	{
		problem:'046.png', 
		answer:'归心似箭',
		disturb:'归心似箭忍者神龟浪迹天涯',
		description:'想回家的心情像射出的箭一样急。形容回家心切。'
	},
	{
		problem:'047.jpg', 
		answer:'添油加醋',
		disturb:'添油加醋砖瓦枝接叶盐着锅',
		description:'比喻叙述事情或转述别人的话时，为了夸大，或为了引起别人的注意而添上原来没有的内容。'
	},
	{
		problem:'048.jpg', 
		answer:'长途跋涉',
		disturb:'长途跋涉海登山类聚群分岳',
		description:'跋涉：翻山越岭、趟水过河。指远距离的翻山渡水。形容路途遥远，行路辛苦。'
	},
	{
		problem:'049.jpg', 
		answer:'提心吊胆',
		disturb:'提心吊胆战惶失措临深履薄',
		description:'形容十分担心或害怕。'
	},
	{
		problem:'050.jpg', 
		answer:'挥金如土',
		disturb:'挥金如土粪钱财泥穷奢极侈',
		description:'把钱财当成泥土一样任意挥霍。形容挥霍浪费到了极点。'
	},
	{
		problem:'051.jpg', 
		answer:'人模狗样',
		disturb:'人模狗样身体头张冠李戴犬',
		description:'身份是人，举止形容却像狗。多用于嘲讽。'
	},
	{
		problem:'053.jpg', 
		answer:'精打细算',
		disturb:'精打细算克勤克俭精兵简政',
		description:'打：规划。意思是精密地计划，详细地计算。指在使用人力、物力时计算得很精细。'
	},
	{
		problem:'052.jpg', 
		answer:'狐朋狗友',
		disturb:'狐朋狗友群党狼狈为奸犬猫',
		description:'比喻品行不端的朋友。'
	},
	{
		problem:'055.jpg', 
		answer:'衣食父母',
		disturb:'衣食父母以子无忧贵人善忘',
		description:'踏入社会都靠父母提供。指生活所依赖的人。'
	},
	{
		problem:'054.jpg', 
		answer:'狗仗人势',
		disturb:'狗仗人势欺傍狐假虎威洞宾',
		description:'比喻仗势欺人（骂人的话）。'
	},
	{
		problem:'056.jpg', 
		answer:'痴鼠拖姜',
		disturb:'痴鼠拖姜目寸光桂之性谋皮',
		description:'亦作“痴鼠拖薑”。比喻不聪明的人自找麻烦。《儿女英雄传》第二二回：“按俗語説便叫作‘賣盆的自尋的’；掉句文便叫作‘痴鼠拖薑，春蠶自縛’！'
	}
]
